# fly.toml app configuration file generated for playdoh on 2025-06-10T03:02:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'playdoh'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
